### PR TITLE
Making TLP and PAP taxonomy adhere to FIRST standard (color and uppercase value)

### LINKED ISSUE #86: Make TLP taxonomy adhere to FIRST TLP v1.0 standard
That means: uppercase, match colours, etc. But more importantly: the updated definition of TLP:AMBER. See https://www.first.org/tlp/

### PR DESCRIPTION
**Pull request by vba-anssi**
Hello, in order to fix #86:

- Changing PAP:WHITE value to PAP:CLEAR for consistency between TLP and PAP taxonomy
- Changing PAP tags colors to match TLP tags colors
- Changing TLP tag values to uppercase to follow FIRST standard

### CODE REVIEW

**Comment by adulau** [comment]
Thanks a lot for the pull-request. 

Before merging, I would propose the following (let me know what you think):

- To keep the `PAP:WHITE` in addition to `PAP:CLEAR` as there is already a lot of tools which are using the tags. For backward compatibility, I would keep it just like we did for `TLP:WHITE`.

**Comment by vba-anssi** [comment]
Keeping both tags is a good solution. I added it back.

Thanks for your fast answer  !

**Comment by adulau** [comment]
Thank you for the quick update. I'll review the CI tomorrow and check for the TLP namespace part being uppercase.

**Comment by adulau** [comment]
We will need to review the code base in MISP about the exclusion handling like we did for TLP before merging it.

**Comment by adulau** [comment]
Based on our discussion at FIRST-CTI, I made two commits based on your pull-request 873fc6209fd247920635824c755023ab6787ae62 and 6efa8c30757930109fbc96d6f582532882d15bc9. This should solve the pending issue. We will announce the change in the next release of MISP in the next days. 

Thanks again for your work. I'll add the reference to [CERT-FR sharing policy](https://www.cert.ssi.gouv.fr/csirt/sharing-policy/) in the blog post.

**Pull request closed without merging**
