### PR TITLE
Microsoft's Computer Antivirus Research Organization implementation f…

### PR DESCRIPTION
**Pull request by SDOIR**
Microsoft's Computer Antivirus Research Organization implementation for malware classification.

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much for your contribution.

**Comment by SDOIR** [comment]
My pleasure. I do have a longer version also which also includes all malware families published in Microsoft's SIRs since 2008 until the most recent one, but thought it would be an overkill. Let me know if its not and I will create another pull request.

**Comment by adulau** [comment]
Nice. We plan to have soon an easy search interface for the taxonomy in MISP (cc @iglocska) that could be useful for the such huge list.  So when you have time, the PR is more than welcome. Again thank you for your help.

**Comment by SDOIR** [comment]
Awesome. I'll do some polishing and then PR once ready.

**Pull request merged**
