### PR TITLE
add pentext taxonomy

### PR DESCRIPTION
**Pull request by gianninou**

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much for the PR. Would it be possible to list all the references used for this taxonomy? I have seen some known descriptions from OWASP and alike.

**Comment by gianninou** [comment]
Yes sur, I had it on the json in a comment block ?

**Comment by adulau** [comment]
@gianninou You can add it in the description directly. Thanks a lot.

**Comment by adulau** [comment]
Thank you very much for the pentesting taxonomy. I'll update the document and publish with the others.

**Pull request merged**
