### PR TITLE
ENISA SoD Matrix for CSIRT, LEA, JUD, PROSEC

### PR DESCRIPTION
**Pull request by cudeso**

### CODE REVIEW

**Comment by adulau** [comment]
Thanks a lot for this new taxonomy. I just have a question about the actors field, what is the idea behind this field? We don't have it until now in the taxonomy format. We have the idea to add a meta field to expand it a bit if needed.

**Comment by cudeso** [comment]
Indeed, it's not used by MISP. I initially wrote the json (https://github.com/cudeso/SoD-Matrix/blob/master/machinetag.json) to create the SoD table (https://github.com/cudeso/SoD-Matrix) which describes the actors per activity. 

I noticed MISP ignores the taxonomy fields that it doesn't use. So instead of having to maintain two json files (one for MISP, one to create the table), I kept the single file. I can remove it if needed, I then just need to alter the machinetag2human.py a bit so it generates a taxonomy-json without the optional field.

**Comment by cudeso** [comment]
@adulau maybe have a meta field that can contain multiple types of values? There should be a meta field then per entry/value. And maybe also one per predicate.

```
 "meta": 
 [ { "field1": "xyz"} , { "field2": "abc"}, { "field3": [ ... ]  }, { "field4": [ ... ] } ] 
```
I can convert it to 
"meta": [
 { "actors": [ ... ] }
 ]

**Comment by adulau** [comment]
We had some internal discussions and looking more and more. It would make sense to make a galaxy in a matrix-like format. It would be easier to represent all the fields but also for the users to pick the right value. Let me know it you need some help.

**Comment by cudeso** [comment]
Yes, this would make more sense. Also because of the instead of merely indicating the actors by "x", they would also maybe have a designation such as R (resp), C (consult). I'll look into it one of the next coming days. If I need help I'll reach out on Gitter ;-).

**Comment by adulau** [comment]
I suppose we can close this one as is now a galaxy. Thanks a lot

**Pull request closed without merging**
